### ISSUE TITLE
DataService data.by('metadata.namespace') clobbers data

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-common#134]
We often do:
```JavaScript 
var foo = data.by('metadata.name');
// foo = {name1: {}, name2: {}, name3: {}}
```
Which seems to assume that each key will be a single object.  But:
```JavaScript 
var foo = data.by('metadata.namespace');
// should be able to create arrays:
// foo = {namespace1: [many], namespace2: [many], namespace3: [many]}
```
But instead the last object will win, clobbering all of the previously assigned objects.
```JavaScript 
var foo = data.by('metadata.namespace');
// should be able to create arrays:
// foo = {namespace1: {oops}, namespace2: {oops}, namespace3: {oops}}
```

The simple fix that would break all of our code (yay, all the things!) would be to always return an array:
```JavaScript 
var foo = data.by('metadata.name');
// foo = {name1: [{}], name2: [{}], name3: [{}]}
var foo2 = data.by('metadata.namespace');
// foo = {namespace1: [{}], namespace2: [{}], namespace3: [{}]}
```
I'm not sure if there is a realistic way to fix this.  If not, an alt might be to update it to something like `data.byName()` & eliminate the implication that it should be able to sort by any key (but even that would be a big refactor).

@spadgett

**Comment by spadgett** [comment]
This is by design, although maybe should be documented more clearly. It's basically `_.keyBy` where it assumes the key will be unique.

If we need an array back, we could add a new method like `data.groupBy` or `data.collectionBy` without breaking existing callers.

**Comment by benjaminapetersen** [comment]
Ok, great. I'm good with either, maybe preference to `groupBy` but not strong. 

I don't know if its a huge deal, other than consistency.  I suppose we could go the other direction & just use `_`. Hmm.

**Comment by spadgett** [comment]
To this point, we've just used lodash for this. I'd lean towards using lodash instead of trying to reimplement their collections in DataService.
