### ISSUE TITLE
NotificationsService memory leak and issues

### ISSUE THREAD

**Issue by dtaylor113** [openshift/origin-web-common#220]
The notification service leaks memory because it keeps all notifications even after they're no longer displayed.

Also,  [isNotificationVisible](https://github.com/openshift/origin-web-common/blob/master/src/ui-services/notificationsService.js#L27) should return false if it's drawer only.  The intended use of this function was to avoid showing two toast notifications.   

Some additional comments by @spadgett:

"I think it would be better to just not keep an array of notifications.  Notification service `addNotification` just broadcasts a message and is done then the toasts notification component can make sure it's not showing the same one twice and drawer tracks current notifications and if they've been cleared itself"

Another issue is that there is now way for user to 'restore' permanently hidden notifications.

**Comment by benjaminapetersen** [comment]
I wonder if we can consolidate some tracking as well, `EventsService` (in web-console) is also tracking & storing info in `localStorage`.  Events & Notifications are different objects, so it might be fine, but worth a thought.
