### ISSUE TITLE
Add an app directory with a simple test to verify this works

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-common#32]
Prob just login & list some resources would be sufficient initially & would help encourage us to write tests, etc.

**Comment by dtaylor113** [comment]
Hi @benjaminapetersen, can you please elaborate on this?  We do currently have unit tests.

**Comment by benjaminapetersen** [comment]
Sure thing.  How much unit test coverage do we have on this?  I haven't run the reports on this repo recently.  Was thinking also some e2e style so we stay confident in changes as we make them.  

The `bower link` trick makes it a lot easier to be confident in changes here, but still think we could improve.

**Comment by jeff-phillips-18** [comment]
Good candidate for hack day!

**Comment by benjaminapetersen** [comment]
Yeah might be
