### ISSUE TITLE
delete-project component shows both toast and in-page alert

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-common#59]
If you pass `alerts` to the `delete-project` component, it shows both a toast and an in-page alert.

![screen shot 2017-05-05 at 8 41 05 am](https://cloud.githubusercontent.com/assets/1167259/25745786/9cbf1880-316e-11e7-8723-a2cc7b241151.png)

If you don't pass alerts, it results in a runtime error.

It makes sense to me to use the alerts when they're passed in and use toasts when they aren't.

![openshift web console 2017-05-05 08-38-33](https://cloud.githubusercontent.com/assets/1167259/25745703/3c4cc9de-316e-11e7-9b93-6445c1f61e75.png)

@jwforres @jeff-phillips-18

**Comment by serenamarie125** [comment]
@spadgett what does this mean from a user experience perspective?  It seems odd that sometimes they will get a toast and others an inline, but i'm not sure in which use cases the delete-project component is used.

**Comment by spadgett** [comment]
@serenamarie125 Yeah we could just make it always toast. https://github.com/openshift/origin-web-console/pull/1521 makes it a toast rather than inline alert, which is consistent with the new landing page. I don't believe the component is used anywhere else.
