### ISSUE TITLE
Ensure derivative service of DataService match function signatures when possible

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/origin-web-common#96]
Per [this comment](https://github.com/openshift/origin-web-console/pull/1599#discussion_r120724932) originally, if possible lets match `DataService` API when we create new services to abstract away logic:

```JavaScript 
// example:
DataService.get(resource, name, context, opts)
// current:
BindingService.bindService(context, name, application)
// ideal:
BindingService.bindService(name, context, opts) // where application prob could be part of context or opts, depending on its internal usage 
```
I'm a fan of these services to keep controllers, directives, etc clean, just want to make sure we maintain consistency.

@jwforres @jeff-phillips-18

**Comment by spadgett** [comment]
Hey @benjaminapetersen I think this is reasonable, and we can watch for it in code reviews. The signature of these particular methods have changed since the issue was opened, so I'm going to call this "closed."

**Comment by benjaminapetersen** [comment]
Sounds good!
