### ISSUE TITLE
truncate when exact character count results in ellipsis and "See All" even though there is nothing more

### ISSUE THREAD

**Issue by rhamilto** [openshift/origin-web-common#98]
Character count is exact match for truncate, so . is removed, ... and See All is added.
![screen shot 2017-06-08 at 9 37 38 am](https://user-images.githubusercontent.com/895728/26932844-c59eb20e-4c32-11e7-8ce6-b8a5242774f2.PNG)

Clicking "See All" restores the .
![screen shot 2017-06-08 at 9 37 43 am](https://user-images.githubusercontent.com/895728/26932845-c5a28b7c-4c32-11e7-9347-eee86be7ada1.PNG)

**Comment by spadgett** [comment]
Reopening as I don't believe this particular problem is fixed even though other truncate bugs are fixed.

**Comment by cdcabrera** [comment]
@spadgett as a possible solution to helping close this issue down, what's the take on implementing a unit test around toast notifications within this repository?
